### PR TITLE
Update peerDependencies to support Grunt 1.0

### PR DESCRIPTION
**Pull request by grunt-updater2**
Update peerDependencies to support Grunt 1.0

Hello,

This is an automated issue request to update the `peerDependencies` for your Grunt plugin.
We ask you to merge this and **publish a new release on npm** to get your plugin working in Grunt 1.0!

Read more here: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
Also on Twitter: https://twitter.com/gruntjs/status/700819604155707392

If you have any questions or you no longer have time to maintain this plugin, then please let us know in this thread.

Thanks for creating and working on this plugin!

(P.S. Close this PR if it is a mistake, sorry)

### CODE REVIEW

**Comment by ricky** [comment]
@zero5100 Are you the current maintainer? Can we get this merged so that this package can be used w/ grunt 1.0?

**Comment by zero5100** [comment]
Is changing the dep to `"grunt": ">=0.4.0"` the best way to do it or should we target a more specific version of grunt? This change should probably be merged into develop first but I haven't looked at the diff between develop and master in awhile.

**Comment by ricky** [comment]
Given that it's currently pinned to `~0.4.2`, `>=0.4.2` may be more appropriate. I don't think you want to go higher, as it _does_ still work with grunt 0.4.x, and you don't want to force users to upgrade. It merely opens the door for people who wish to try with a newer version of grunt.

Merging into `develop` seems to have been the previous process, although given that this project seems mostly abandoned I don't know how much that matters. (This PR was created by an automated process from `grunt`.) It appears that `develop` is actually _behind_ master.

**Comment by zero5100** [comment]
Alright, sounds good to me. I'll take a look at the develop/master thing when I have some time and then get this merged in.

**Comment by bgaillard** [comment]
Hi @zero5100, we also encounter problems with grunt 1.x. 

```console
npm ERR! peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-flyway@0.2.1 wants grunt@~0.4.2
npm ERR! peerinvalid Peer grunt-shell@1.3.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer load-grunt-tasks@3.5.2 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-clean@1.0.0 wants grunt@>= 0.4.5
```

Do you mind if I create a new `0.3.0` version today ? 

Thanks

**Comment by zero5100** [comment]
Sure thing. I should have a few hours today to clean up this repo and get this and the v3 changes merged in to develop as well.

**Comment by zero5100** [comment]
I actually just created 0.3.0 version based on the current master. I am working on getting flyway v3.2 merged into master and I will update the grunt version as well and create a new 0.3.2 release shortly.

**Comment by zero5100** [comment]
Merged into develop from #12, new version 0.3.2 on the way.

**Comment by bgaillard** [comment]
Hi @zero5100 and thanks so much for all those updates :+1: 

For now the package is not published on npmjs.org, so can I publish it now ? Also if you want I can add you as a collaborator on the project on npmjs.org to let you publish new versions yourself, do you have an account on npmjs.org and what is your pseudo ?

**Comment by zero5100** [comment]
Thanks @bgaillard, happy to help. I haven't published to npm before so I just created an account on there. My account is [zero5100](https://www.npmjs.com/~zero5100) on npmjs. I'll need to figure out how publishing works but in the future I will publish a new version to npm when I create a release. Thanks!

**Comment by bgaillard** [comment]
Ok, I added you as an additionnal owner on the npmjs repository and published version 0.3.2 https://www.npmjs.com/package/grunt-flyway. 

Thanks again for your work !

**Pull request closed without merging**
