### PR TITLE
Update to flyway version 3.2.1

### PR DESCRIPTION
**Pull request by zero5100**
* Update from flyway 3.0 to 3.2.1
* Add support for repair and info commands
* Package in jdbc drivers, as is standard since flyway 3.1
* Update package version to 3.0 to denote breaking changes
* Readme.md has been updated

### CODE REVIEW

**Comment by zero5100** [comment]
Anything? We have been using this branch in production without issue since this PR was created.

**Comment by brock-civitas** [comment]
It would be greatly appreciated if this could get released!  Need to be able to run callbacks :smile:

**Comment by bgaillard** [comment]
Hi guys, sorry because we do not have time to maintain this plugin :(.

Are you interesting to be a collaborator on the project to help us update it ? 

Thanks,

Baptiste

**Comment by zero5100** [comment]
I'm up for it. I will be using it for the foreseeable future anyway, so I will probably be updating my fork with newer versions of flyway at least.

**Comment by bgaillard** [comment]
Ok great, so welcome ! I added you as a collaborator, you now have write rights, i'm not used to do this, is it sufficient to let you merge this PR ? 

Thanks.

**Comment by zero5100** [comment]
Thanks! Yep, it looks like I am able to merge it. I will merge this over into the develop branch, and then update the readme for the new version. What is the normal process for merging to master and tagging?

**Comment by bgaillard** [comment]
We're used to work with this GIT Workflow https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow. 

But in most cases we only keep 2 branches, the `master` and `develop` branches. 

We always develop in the `develop` branch, then when everything is ok and well tester on the `develop` branch we merge the `develop` branch into the master branch. 

Finally, have the merge on `master` we create a new tag on master being careful with SEMVER to create the new version number.

Is this ok for you ?

**Comment by zero5100** [comment]
Yep, that is perfect. That is the process that I am used to. Is there anyone that would like to review the changes in develop before they are merged into master?

**Pull request merged**
